apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-with-docs
  description: Service with docs
  annotations:
    backstage.io/techdocs-ref: dir: .
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
